### PR TITLE
Slim4 Support w/ Test updates

### LINKED ISSUE #48: Add support for Slim 4
Hi,

Thank you for your work on this package.

It seems that Slim 4 is currently not supported. Middlewares in Slim 4 no longer receive `$next` as the third argument, so this makes it incompatible with this package at this time.

See the Middleware doc for v3 (http://www.slimframework.com/docs/v3/concepts/middleware.html) and v4 (http://www.slimframework.com/docs/v4/concepts/middleware.html) to compare.

### PR DESCRIPTION
**Pull request by stephenkuhn214**
Update to use Slim version 4.

### CODE REVIEW

**Comment by stephenkuhn214** [comment]
@DavidePastore anything else that needs to be done to this so it can be merged to allow for Slim4 compatibility?

**Comment by travis-vandame** [comment]
@DavidePastore @stephenkuhn214 Are there plans to get this merged in?

**Comment by stephenkuhn214** [comment]
@travis-vandame I'm just waiting on @DavidePastore  to approve and merge it.

**Comment by DavidePastore** [comment]
Hi @stephenkuhn214. Thank you for this PR! Could you please rebase it from the `4.0` branch? You can completely remove the `composer.lock` file since this is not required anymore (dependencies will be installed based on the PHP version the users are using).

**Comment by stephenkuhn214** [comment]
@DavidePastore I've removed the composer.lock file, but I'm not sure how you want me to rebase my fork using your 4.0 branch.  Do I need to for your 4.0 branch first and then rebase in my repo using that?

**Comment by DavidePastore** [comment]
@stephenkuhn214, I managed to fix some issues that we were facing. I tried to support older versions (PHP 7.1) of PHP but unfortunately, this is not possible because of the [wrong usage of the `provide` section in `composer.json` in older versions of the `slim/http` package](https://github.com/slimphp/Slim-Http/pull/138).  We have two missing things:
* [x] documentation should be updated (README.md);
* [x] the PHPUnit configuration should be changed ([check the warnings that appear during the build](https://github.com/DavidePastore/Slim-Validation/actions/runs/3708985983/jobs/6287113196)).

**Comment by stephenkuhn214** [comment]
@DavidePastore README has been updated to mention requiring Slim 4.  I didn't see anything else in there that seemed to need updating.
The PHPUnit config was updated to have that <coverage> block per the requirements of PHPUnit 9.5.  Looks like the build is using PHPUnit 8.5.  Not sure how you want to proceed with differing xml configs between versions.

When running it locally for me, composer installed PHPUnit 9.5 even though it only requires ^8.0, so I had change the xml file to match my installation because it was failing.  If we want to support PHPUnit 8, I can change the config file back, but it won't work for ^9.0.

**Comment by DavidePastore** [comment]
@stephenkuhn214, thank you for the additional update you did on the README.md file. What I can see is that the instructions you can find on the [Slim 4 documentation](https://www.slimframework.com/docs/v4/) are different than the ones that are stated in this branch README.md (e.g. how to instantiate the Slim application). Could you please fix it?
Regarding the currently used PHPUnit version, [it supports PHP 7.2](https://phpunit.de/supported-versions.html). Are you sure that you removed the `composer.lock` file before launching `composer install`?

**Comment by stephenkuhn214** [comment]
@DavidePastore README.md has been updated with the Slim4 app instantiation instructions.  Sorry I missed that the first time!
Regarding the PHPUnit version I was using, yes you're correct, it must have been because of `composer.lock`.  Since that file is removed, I re-ran `composer install` and it installed PHPUnit 8.5 which works correctly now that you reverted my changes in the config file to use `<filter>` instead of `<coverage>`.

**Comment by DavidePastore** [comment]
Perfect @stephenkuhn214, thank you for the changes!

**Comment by DavidePastore** [comment]
Released here: https://github.com/DavidePastore/Slim-Validation/releases/tag/v4.0.0

**Pull request merged**
