### PR TITLE
Slim 4 support

### PR DESCRIPTION
**Pull request by M-Shahbaz**
Please update for slim 4 support and also respect version to 2
Thanks,

### CODE REVIEW

**Comment by DavidePastore** [comment]
Hi @M-Shahbaz . Thanks for you PR but I see that most of the tests don't work correctly. You have to be sure to also update the Slim version used in the `composer.json` file and the logic behind tests.

**Comment by M-Shahbaz** [comment]
Hi @DavidePastore . Thanks for your response, I'll try to update asap.

**Comment by necrox87** [comment]
@DavidePastore please merge @M-Shahbaz fix, thanks

**Comment by DavidePastore** [comment]
Hi @necrox87. I can't merge this PR because [the build process failed](https://travis-ci.org/github/DavidePastore/Slim-Validation/builds/723953761?utm_source=github_status&utm_medium=notification). It's necessary to fix tests.

**Comment by willbonde** [comment]
Is this still just needing tests updated so they pass?

**Comment by DavidePastore** [comment]
Hi @willbonde. Yes, tests are still necessary.

**Comment by DavidePastore** [comment]
Superseded by https://github.com/DavidePastore/Slim-Validation/pull/61

**Pull request closed without merging**
